name: "image_classifier"
platform: "tensorflow_savedmodel"
max_batch_size: 8
input [
  {
    name: "input_image"
    data_type: TYPE_FP32
    dims: [224, 224, 3]
  }
]
output [
  {
    name: "probabilities"
    data_type: TYPE_FP32
    dims: [1000]
  }
]