name: "sentiment_analyzer"
platform: "invalid_platform_name"
max_batch_size: 32

input [
  {
    name: "text_input"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]

output [
  {
    name: "sentiment_score"
    data_type: TYPE_FP32
    dims: [ 1 ]
  }
]