FROM ghcr.io/laude-institute/t-bench/ubuntu-24-04:20250624

ENV DEBIAN_FRONTEND=noninteractive

# Install python3-pip and create python symlink
RUN apt-get update && \
    apt-get install -y python3-pip && \
    ln -s /usr/bin/python3 /usr/bin/python && \
    rm -rf /var/lib/apt/lists/*

# Install test dependencies
RUN pip3 install --no-cache-dir --break-system-packages pytest==8.4.1 pandas==2.3.2 scipy==1.16.1

RUN mkdir -p /home/challenge/grids /home/challenge

COPY data/grids/grid_01.txt /home/challenge/grids/grid_01.txt
COPY data/grids/grid_02.txt /home/challenge/grids/grid_02.txt
COPY data/grids/grid_03.txt /home/challenge/grids/grid_03.txt
COPY data/grids/grid_04.txt /home/challenge/grids/grid_04.txt
COPY data/grids/grid_05.txt /home/challenge/grids/grid_05.txt
COPY data/grids/grid_06.txt /home/challenge/grids/grid_06.txt
COPY data/grids/grid_07.txt /home/challenge/grids/grid_07.txt
COPY data/grids/grid_08.txt /home/challenge/grids/grid_08.txt

WORKDIR /home/challenge

# Mapped from docker-compose.yaml
ENV TEST_DIR=/tests
