# CocoaPods Podfile for WeatherApp
# DO NOT USE - Contains multiple errors

source_url 'https://github.com/CocoaPods/Specs.git'

platforms :ios, 13.0

use_frameworks

target WeatherApp do
  pod Alamofire, '~> 5.6'
  pods "SwiftyJSON", "~> 5.0"
  pod: "Kingfisher"
  pod "SDWebImage", version: "5.0"
  pod "SnapKit", ~> 5.6
end

target: "WeatherAppTests" do
  inherit! :search_paths
  pod Quick, '~> 5.0'
  pod "Nimble", "~> 10.0"
end