CC=gcc
CXX=g++
CFLAGS=-O3 -Wall -DNDEBUG
CXXFLAGS=-O3 -Wall -std=c++11 -DNDEBUG

# Optimization flags
OPT_FLAGS=-march=native -flto

# Feature flags for SAT solver preprocessing
ENABLE_PREPROCESSING=1
ENABLE_VIVIFICATION=0
ENABLE_SUBSUMPTION=1
ENABLE_VARIABLE_ELIMINATION=1
ENABLE_BLOCKED_CLAUSE=1

# Preprocessor definitions
DEFINES=-DUSE_PREPROCESSING

ifeq ($(ENABLE_VIVIFICATION),1)
  DEFINES+=-DENABLE_VIVIFICATION
endif

ifeq ($(ENABLE_SUBSUMPTION),1)
  DEFINES+=-DENABLE_SUBSUMPTION
endif

ifeq ($(ENABLE_VARIABLE_ELIMINATION),1)
  DEFINES+=-DENABLE_VARELIM
endif

ifeq ($(ENABLE_BLOCKED_CLAUSE),1)
  DEFINES+=-DENABLE_BCE
endif

# Linker flags
LDFLAGS=-lpthread -lz