name: "recommender"
platform: "tensorflow_savedmodel"
max_batch_size: 16

input [
  {
    name: "user_features"
    data_type: TYPE_FP32
    dims: [100]
  },
  {
    name: "item_features"
    data_type: TYPE_FP32
    dims: [-1, -1]
  }
]

output [
  {
    name: "scores"
    data_type: TYPE_FP32
    dims: []
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]